# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

def install_pods
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'R.swift'                            , '~> 4.0.0'
    pod 'SlideMenuControllerSwift'           , '~> 4.0.0'
    pod 'SnapKit'                            , '~> 4.0.1'
    pod 'SVProgressHUD'                      , '~> 2.2.5'
    pod 'NCMB'                               , :git => 'https://github.com/NIFCloud-mbaas/ncmb_ios.git'
    pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
    pod 'MaterialControls'
    # Pods for FiMap
end

target 'SalesIncome' do
    install_pods
end

swift4_names = [
'R.swift',
'SlideMenuControllerSwift',
'SnapKit',
]

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if swift4_names.include? target.name
                config.build_settings['SWIFT_VERSION'] = "4.0"
                else
                config.build_settings['SWIFT_VERSION'] = "4.2"
            end
        end
    end
end
